add wave -position end  sim:/a_test_aes_core/UUT/DETECTOR_CODE/s_parity_data_in
add wave -position end  sim:/a_test_aes_core/UUT/DETECTOR_CODE/s_pt_aligned
add wave -position end  sim:/a_test_aes_core/UUT/DETECTOR_CODE/s_data_in_unmasked
add wave -position end  sim:/a_test_aes_core/UUT/DETECTOR_CODE/data_out
add wave -position end  sim:/a_test_aes_core/UUT/data_in
add wave -position end  sim:/a_test_aes_core/UUT/data_out
add wave -position 5  sim:/a_test_aes_core/UUT/data_in
add wave -position 5  sim:/a_test_aes_core/UUT/data_in
add wave -position 6  sim:/a_test_aes_core/UUT/data_out
add wave -position end  sim:/a_test_aes_core/UUT/data_out
add wave -position 8  sim:/a_test_aes_core/UUT/data_in
add wave -position end  sim:/a_test_aes_core/UUT/data_out
add wave -position 12  sim:/a_test_aes_core/UUT/data_in
add wave -position end  sim:/a_test_aes_core/UUT/data_in
add wave -position end  sim:/a_test_aes_core/UUT/data_out
add wave -position end  sim:/a_test_aes_core/UUT/DETECTOR_CODE/alarm
add divider -position 13 end
add wave -position end  sim:/a_test_aes_core/UUT/round_for(1)/ROUND_I/data_in
add wave -position end  sim:/a_test_aes_core/UUT/round_for(1)/ROUND_I/data_out